apiVersion: v1
kind: Service
spec:
  ports:
    - port: 9009
      protocol: TCP
      name: http-api
  selector:
    app: cortex
metadata:
  name: cortex
  namespace: default
  labels:
    app: cortex
---
apiVersion: v1
kind: Service
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: minio-s3
    - port: 9090
      protocol: TCP
      name: minio-console
  selector:
    app: minio
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
        - image: cortexproject/cortex:v1.15.2
          args:
            - -config.file=/tmp/config.yaml
          env:
            - name: TMPDIR
              value: /data/
          ports:
            - containerPort: 9009
          name: cortex
          volumeMounts:
            - name: config
              mountPath: /tmp/
      volumes:
        - name: config
          configMap:
            name: cortex
metadata:
  name: cortex
  namespace: default
  labels:
    app: cortex
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: quay.io/minio/minio:RELEASE.2023-05-27T05-56-19Z
          args:
            - server
            - /data
            - --console-address
            - :9090
          ports:
            - containerPort: 9000
            - containerPort: 9090
          name: minio
          volumeMounts:
            - name: localvolume
              mountPath: /data/
      volumes:
        - name: localvolume
          emptyDir:
            sizeLimit: 5Mi
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
---
data:
  config.yaml: |
    target: alertmanager,all
    auth_enabled: true
    server:
      http_listen_port: 9009
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
      log_level: debug
    distributor:
      shard_by_all_labels: true
      pool:
        health_check_ingesters: true
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: gzip
    ingester:
      lifecycler:
        min_ready_duration: 0s
        final_sleep: 0s
        num_tokens: 512
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    blocks_storage:
      tsdb:
        dir: /tmp/cortex/tsdb
      bucket_store:
        sync_dir: /tmp/cortex/tsdb-sync
      backend: filesystem
      filesystem:
        dir: ./data/tsdb
    compactor:
      data_dir: /tmp/cortex/compactor
      sharding_ring:
        kvstore:
          store: inmemory
    frontend_worker:
      match_max_concurrent: true
    alertmanager:
      enable_api: true
      external_url: http://localhost
    alertmanager_storage:
      backend: s3
      s3:
        endpoint: minio.default.svc:9000
        secret_access_key: minioadmin
        access_key_id: minioadmin
        insecure: true
        bucket_name: cortex
    ruler:
      enable_api: true
    ruler_storage:
      backend: s3
      s3:
        endpoint: minio.default.svc:9000
        secret_access_key: minioadmin
        access_key_id: minioadmin
        insecure: true
        bucket_name: cortex
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex
  namespace: default
  labels:
    app: cortex
---
apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  containers:
    - image: alpine:3.18
      command:
        - /bin/sh
      name: minio-bucket-creator
      args:
        - -c
        - |-
          # set -x;
          set -o pipefail;

          apk add --no-cache --update curl;

          arch=$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/);
          curl -L -o /usr/bin/mc https://dl.min.io/client/mc/release/linux-${arch}/mc;
          chmod +x /usr/bin/mc;
          /usr/bin/mc alias set local http://minio.default.svc:9000 minioadmin minioadmin;

          echo "Waiting for minio to launch on 9000...";
          while ! nc -z minio.default.svc 9000; do sleep 0.1; done;

          /usr/bin/mc mb local/cortex;
          # /usr/bin/mc tree local/;
metadata:
  name: minio-bucket-creator
  namespace: default
  labels:
    app: minio-bucket-creator

