apiVersion: v1
kind: Service
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: minio-s3
    - port: 9090
      protocol: TCP
      name: minio-console
  selector:
    app: minio
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
        - image: cortexproject/cortex:v1.15.2
          args:
            - -config.file=/tmp/config.yaml
          ports:
            - containerPort: 9009
          name: cortex
          volumeMounts:
            - name: config
              mountPath: /tmp/
      volumes:
        - name: config
          configMap:
            name: cortex
metadata:
  name: cortex
  namespace: default
  labels:
    app: cortex
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: quay.io/minio/minio:RELEASE.2023-05-27T05-56-19Z
          args:
            - server
            - /data
            - --console-address
            - :9090
          ports:
            - containerPort: 9000
            - containerPort: 9090
          name: minio
          volumeMounts:
            - name: localvolume
              mountPath: /data/
      volumes:
        - name: localvolume
          emptyDir:
            sizeLimit: 5Mi
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
---
data:
  config.yaml: |
    auth_enabled: true
    server:
      http_listen_port: 9009
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    distributor:
      shard_by_all_labels: true
      pool:
        health_check_ingesters: true
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: gzip
    ingester:
      lifecycler:
        min_ready_duration: 0s
        final_sleep: 0s
        num_tokens: 512
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    blocks_storage:
      tsdb:
        dir: /tmp/cortex/tsdb
      bucket_store:
        sync_dir: /tmp/cortex/tsdb-sync
      backend: filesystem
      filesystem:
        dir: ./data/tsdb
    compactor:
      data_dir: /tmp/cortex/compactor
      sharding_ring:
        kvstore:
          store: inmemory
    frontend_worker:
      match_max_concurrent: true
    ruler:
      enable_api: true
    ruler_storage:
      backend: s3
      s3:
        endpoint: minio.default.svc:9000
        secret_access_key: minioadmin
        access_key_id: minioadmin
        insecure: true
        bucket_name: cortex
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex
  namespace: default
  labels:
    app: cortex

